version: 2.0
jobs:
  build:
      working_directory: ~/chickn
      docker:
        - image: circleci/clojure:lein-2.8.1-browsers # includes phantomjs
      environment:
        LEIN_ROOT: nbd
        JVM_OPTS: -Xmx3200m
      steps:
        - checkout
        - restore_cache:
            key: chickn-{{ checksum "project.clj" }}
        - run: lein deps
        - save_cache:
            paths:
              - ~/.m2
            key: chickn-{{ checksum "project.clj" }}
        - run: lein testall
