version: 2.1
jobs:
  build:
      working_directory: ~/chickn
      docker:
        - image: circleci/clojure:openjdk-8-lein-buster-node-browsers-legacy
      environment:
        LEIN_ROOT: nbd
        JVM_OPTS: -Xmx3200m
      steps:
        - checkout
        - restore_cache:
            key: chickn-{{ checksum "project.clj" }}
        - run: lein deps
        - run: npm install -g karma karma-cljs-test karma-chrome-launcher karma-firefox-launcher
        - save_cache:
            paths:
              - ~/.m2
            key: chickn-{{ checksum "project.clj" }}
        - run: lein testall
