name: Chickn CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: lein deps
    - name: Install karma
      run: npm install -g karma karma-cljs-test karma-chrome-launcher karma-firefox-launcher
    - name: Run tests
      run: lein testall
