name: Chickn CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@12.3
      with:
        cli: latest
    - name: Install karma
      run: npm install -g karma karma-cljs-test karma-chrome-launcher karma-firefox-launcher
    - name: Run clj tests
      run: clojure -Mtest
    - name: Run chrome cljs tests
      run:  clojure -Mcljs-test -x chrome-headless
    - name: Run firefox cljs tests
      run:  clojure -Mcljs-test -x firefox-headless

